### ISSUE TITLE
  ImportError: cannot import name 'Feature' from 'setuptools'

### ISSUE THREAD

**Issue by git0fun** [zms-publishing/zms3#1]
hi, 

I like this project, but have an issue on installing on a Mac.  Hope you have a solution.

```
ERROR: Command errored out with exit status 1:
     command: /Users/poar/Documents/ZMS3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jw/3jbz7d2d0wb6m5rkp6qkmqbm0000gn/T/pip-install-eh5hv5_z/zope-i18nmessageid/setup.py'"'"'; __file__='"'"'/private/var/folders/jw/3jbz7d2d0wb6m5rkp6qkmqbm0000gn/T/pip-install-eh5hv5_z/zope-i18nmessageid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jw/3jbz7d2d0wb6m5rkp6qkmqbm0000gn/T/pip-pip-egg-info-770yisim
         cwd: /private/var/folders/jw/3jbz7d2d0wb6m5rkp6qkmqbm0000gn/T/pip-install-eh5hv5_z/zope-i18nmessageid/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jw/3jbz7d2d0wb6m5rkp6qkmqbm0000gn/T/pip-install-eh5hv5_z/zope-i18nmessageid/setup.py", line 25, in <module>
        from setuptools import setup, find_packages, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/Users/poar/Documents/ZMS3/lib/python3.8/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by drfho** [comment]
hi, 
ZMS3 works with Py2, not Py3.
With your Py3.8 please try ZMS5 https://github.com/zms-publishing/ZMS5/archive/master.zip
Best regards
f
